export const articleContent = {
  "article1": "Defines the name 'India' and the territory of the Union, including States and Union Territories.",
  "article2": "Empowers Parliament to admit or establish new States into the Union.",
  "article3": "Allows Parliament to form new States or alter areas, boundaries, or names of existing States.",
  "article4": "Specifies that laws under Articles 2 and 3 can amend Schedules and include supplemental provisions.",
  "article5": "Determines citizenship status at the Constitution's commencement on January 26, 1950.",
  "article6": "Grants citizenship to certain persons who migrated to India from Pakistan.",
  "article7": "Addresses citizenship for persons who migrated to Pakistan but returned to India.",
  "article8": "Provides citizenship to persons of Indian origin residing abroad under specific conditions.",
  "article9": "Declares that persons voluntarily acquiring foreign citizenship lose Indian citizenship.",
  "article10": "Ensures the continuation of citizenship rights subject to legal provisions.",
  "article11": "Authorizes Parliament to enact laws regulating citizenship.",
  "article12": "Defines 'State' to include government, Parliament, and State Legislatures for Part III.",
  "article13": "Voids laws inconsistent with or in derogation of fundamental rights.",
  "article14": "Guarantees equality before law and equal protection of laws to all persons.",
  "article15": "Prohibits discrimination by the State on specified grounds.",
  "article16": "Ensures equal opportunity in public employment, with provisions for reservations.",
  "article17": "Abolishes untouchability and forbids its practice in any form.",
  "article18": "Prohibits conferment of titles by the State, except military or academic distinctions.",
  "article19": "Protects freedoms of speech, expression, assembly, association, movement, and residence.",
  "article20": "Provides safeguards against ex post facto laws, double jeopardy, and self-incrimination.",
  "article21": "Ensures no person is deprived of life or liberty except by procedure established by law.",
  "article21A": "Mandates free and compulsory education for children aged 6 to 14 years.",
  "article22": "Provides safeguards against arbitrary arrest and detention, including right to counsel.",
  "article23": "Prohibits human trafficking, forced labor, and similar practices.",
  "article24": "Bans employment of children below 14 in factories, mines, or hazardous work.",
  "article25": "Guarantees freedom of conscience and the right to practice and propagate religion.",
  "article26": "Allows religious denominations to manage their religious affairs.",
  "article27": "Prohibits taxes for promoting any particular religion.",
  "article28": "Restricts religious instruction in State-funded educational institutions.",
  "article29": "Protects cultural and educational rights of minorities.",
  "article30": "Grants minorities the right to establish and administer educational institutions.",
  "article32": "Provides the right to approach the Supreme Court for enforcement of fundamental rights.",
  "article33": "Allows Parliament to modify fundamental rights for armed forces and police.",
  "article34": "Permits restrictions on fundamental rights in areas under martial law.",
  "article35": "Empowers Parliament to enact laws to implement fundamental rights provisions.",
  "article36": "Defines 'State' for the purposes of Part IV, as in Part III.",
  "article37": "States that Directive Principles are not enforceable but fundamental to governance.",
  "article38": "Directs the State to promote welfare through a just social, economic, and political order.",
  "article39": "Outlines principles like equitable wealth distribution and prevention of resource concentration.",
  "article39A": "Promotes equal justice and mandates free legal aid for disadvantaged citizens.",
  "article40": "Directs the State to organize village panchayats as units of self-government.",
  "article41": "Encourages the State to secure work, education, and assistance for the needy.",
  "article42": "Mandates just and humane work conditions and maternity relief.",
  "article43": "Promotes a living wage and decent working conditions for workers.",
  "article43A": "Encourages worker participation in the management of industries.",
  "article44": "Directs the State to secure a uniform civil code across India.",
  "article45": "Mandates early childhood care and education for children below six years.",
  "article46": "Promotes educational and economic interests of Scheduled Castes, Tribes, and weaker sections.",
  "article47": "Directs the State to improve nutrition, living standards, and public health.",
  "article48": "Promotes modern and scientific organization of agriculture and animal husbandry.",
  "article48A": "Mandates protection and improvement of environment, forests, and wildlife.",
  "article49": "Directs the State to protect monuments and places of national importance.",
  "article50": "Mandates separation of judiciary from the executive in public services.",
  "article51": "Encourages the State to promote international peace and security.",
  "article51A": "Lists duties of citizens, including respecting the Constitution and promoting harmony.",
  "article52": "Establishes the office of the President of India.",
  "article53": "Vests the executive power of the Union in the President.",
  "article54": "Outlines the process for electing the President.",
  "article55": "Details the manner of the President's election, including electoral college.",
  "article56": "Specifies the President's term of office as five years.",
  "article57": "Allows the President to be eligible for re-election.",
  "article58": "Lists qualifications for election as President.",
  "article59": "Sets conditions for the President's office, including restrictions on other roles.",
  "article60": "Prescribes the oath or affirmation for the President.",
  "article61": "Outlines the procedure for impeaching the President.",
  "article62": "Provides for elections to fill vacancies in the President's office.",
  "article63": "Establishes the office of the Vice-President of India.",
  "article64": "Designates the Vice-President as ex-officio Chairman of the Council of States.",
  "article65": "Allows the Vice-President to act as President during vacancies or absence.",
  "article66": "Outlines the process for electing the Vice-President.",
  "article67": "Specifies the Vice-President's term of office as five years.",
  "article68": "Provides for elections to fill vacancies in the Vice-President's office.",
  "article69": "Prescribes the oath or affirmation for the Vice-President.",
  "article70": "Addresses the discharge of President's functions in contingencies.",
  "article71": "Handles disputes and matters related to Presidential and Vice-Presidential elections.",
  "article72": "Grants the President power to pardon, reprieve, or commute sentences.",
  "article73": "Defines the extent of the Union's executive power.",
  "article74": "Establishes a Council of Ministers to aid and advise the President.",
  "article75": "Details provisions for the appointment and role of Ministers.",
  "article76": "Provides for the appointment and duties of the Attorney-General.",
  "article77": "Regulates the conduct of Union Government business.",
  "article78": "Outlines the Prime Minister's duties to inform the President.",
  "article79": "Constitutes Parliament with the President, Council of States, and House of the People.",
  "article80": "Details the composition of the Council of States (Rajya Sabha).",
  "article81": "Details the composition of the House of the People (Lok Sabha).",
  "article82": "Provides for readjustment of constituencies after each census.",
  "article83": "Specifies the duration of the Houses of Parliament.",
  "article84": "Lists qualifications for membership of Parliament.",
  "article85": "Regulates sessions, prorogation, and dissolution of Parliament.",
  "article86": "Grants the President the right to address and send messages to Parliament.",
  "article87": "Provides for a special address by the President at the start of sessions.",
  "article88": "Allows Ministers and the Attorney-General to speak in Parliament.",
  "article89": "Provides for the Chairman and Deputy Chairman of the Council of States.",
  "article90": "Details the vacation of the Deputy Chairman’s office.",
  "article91": "Outlines duties of the Deputy Chairman or acting Chairman.",
  "article92": "Prohibits the Chairman from presiding during a removal resolution.",
  "article93": "Provides for the Speaker and Deputy Speaker of the House of the People.",
  "article94": "Details the vacation of the Speaker’s or Deputy Speaker’s office.",
  "article95": "Outlines duties of the Deputy Speaker or acting Speaker.",
  "article96": "Prohibits the Speaker from presiding during a removal resolution.",
  "article97": "Provides for salaries of the Chairman, Deputy Chairman, Speaker, and Deputy Speaker.",
  "article98": "Establishes a separate secretariat for each House of Parliament.",
  "article99": "Requires members of Parliament to take an oath or affirmation.",
  "article100": "Regulates voting, quorum, and proceedings in Parliament.",
  "article152": "Defines 'State' for Part VI, excluding Jammu and Kashmir.",
  "article153": "Establishes the office of the Governor for each State.",
  "article154": "Vests the executive power of a State in the Governor.",
  "article155": "Provides for the appointment of Governors by the President.",
  "article156": "Specifies the Governor’s term of office as five years.",
  "article157": "Lists qualifications for appointment as Governor.",
  "article158": "Sets conditions for the Governor’s office.",
  "article159": "Prescribes the oath or affirmation for the Governor.",
  "article160": "Addresses discharge of Governor’s functions in contingencies.",
  "article161": "Grants the Governor power to pardon or commute sentences.",
  "article162": "Defines the extent of a State’s executive power.",
  "article163": "Establishes a Council of Ministers to aid and advise the Governor.",
  "article164": "Details provisions for the appointment and role of State Ministers.",
  "article165": "Provides for the appointment and duties of the Advocate-General.",
  "article166": "Regulates the conduct of State Government business.",
  "article167": "Outlines the Chief Minister’s duties to inform the Governor.",
  "article168": "Constitutes State Legislatures with Legislative Assemblies and Councils.",
  "article169": "Allows Parliament to abolish or create Legislative Councils.",
  "article170": "Details the composition of State Legislative Assemblies.",
  "article171": "Details the composition of State Legislative Councils.",
  "article172": "Specifies the duration of State Legislatures.",
  "article173": "Lists qualifications for membership of State Legislatures.",
  "article174": "Regulates sessions, prorogation, and dissolution of State Legislatures.",
  "article175": "Grants the Governor the right to address and send messages to the Legislature.",
  "article176": "Provides for a special address by the Governor at the start of sessions.",
  "article177": "Allows Ministers and the Advocate-General to speak in the Legislature.",
  "article239": "Provides for the administration of Union Territories by the President.",
  "article239A": "Allows creation of Legislatures or Councils for certain Union Territories.",
  "article239AA": "Provides special provisions for the administration of Delhi.",
  "article239AB": "Addresses failure of constitutional machinery in Union Territories.",
  "article240": "Empowers the President to make regulations for certain Union Territories.",
  "article241": "Provides for the establishment of High Courts in Union Territories.",
  "article243": "Defines terms used in Part IX regarding Panchayats.",
  "article243A": "Establishes the Gram Sabha as a body for local governance.",
  "article243B": "Mandates the constitution of Panchayats at village, intermediate, and district levels.",
  "article243C": "Details the composition of Panchayats.",
  "article243D": "Provides for reservation of seats in Panchayats for certain groups.",
  "article243E": "Specifies the duration of Panchayats as five years.",
  "article243F": "Lists disqualifications for Panchayat membership.",
  "article243G": "Outlines the powers, authority, and responsibilities of Panchayats.",
  "article243H": "Authorizes Panchayats to impose taxes and manage funds.",
  "article243I": "Provides for a Finance Commission to review Panchayat finances.",
  "article243J": "Mandates audit of Panchayat accounts.",
  "article243K": "Regulates elections to Panchayats under a State Election Commission.",
  "article243L": "Applies Part IX to Union Territories with modifications.",
  "article243M": "Exempts certain areas from Part IX provisions.",
  "article243N": "Allows continuance of existing Panchayat laws for a limited period.",
  "article243O": "Prohibits court interference in Panchayat electoral matters.",
  "article243P": "Defines terms used in Part IX-A regarding Municipalities.",
  "article243Q": "Mandates the constitution of Municipalities in urban areas.",
  "article243R": "Details the composition of Municipalities.",
  "article243S": "Provides for the constitution of Wards Committees in Municipalities.",
  "article243T": "Provides for reservation of seats in Municipalities for certain groups.",
  "article243U": "Specifies the duration of Municipalities as five years.",
  "article243V": "Lists disqualifications for Municipality membership.",
  "article243W": "Outlines the powers, authority, and responsibilities of Municipalities.",
  "article243X": "Authorizes Municipalities to impose taxes and manage funds.",
  "article243Y": "Provides for a Finance Commission to review Municipality finances.",
  "article243Z": "Mandates audit of Municipality accounts.",
  "article243ZA": "Regulates elections to Municipalities under a State Election Commission.",
  "article243ZB": "Applies Part IX-A to Union Territories with modifications.",
  "article243ZC": "Exempts certain areas from Part IX-A provisions.",
  "article243ZD": "Provides for District Planning Committees for coordinated planning.",
  "article243ZE": "Establishes Metropolitan Planning Committees for metropolitan areas.",
  "article243ZF": "Allows continuance of existing Municipality laws for a limited period.",
  "article243ZG": "Prohibits court interference in Municipality electoral matters.",
  "article243ZH": "Defines terms used in Part IX-B regarding Co-operative Societies.",
  "article243ZI": "Provides for the incorporation of co-operative societies.",
  "article243ZJ": "Details the number and term of board members of co-operative societies.",
  "article243ZK": "Regulates elections of board members of co-operative societies.",
  "article243ZL": "Provides for supersession or suspension of society boards.",
  "article243ZM": "Mandates audit of co-operative society accounts.",
  "article243ZN": "Requires convening of general body meetings for co-operative societies.",
  "article243ZO": "Grants members the right to access information about their society.",
  "article243ZP": "Mandates filing of returns by co-operative societies.",
  "article243ZQ": "Specifies offences and penalties related to co-operative societies.",
  "article243ZR": "Applies provisions to multi-State co-operative societies.",
  "article243ZS": "Applies Part IX-B to Union Territories with modifications.",
  "article243ZT": "Allows continuance of existing co-operative society laws for a limited period.",
  "article244": "Provides for the administration of Scheduled and Tribal Areas.",
  "article244A": "Allows creation of an autonomous State for tribal areas in Assam.",
  "article245": "Defines the extent of legislative powers of Parliament and State Legislatures.",
  "article246": "Distributes legislative powers through Union, State, and Concurrent Lists.",
  "article247": "Allows Parliament to establish additional courts for Union List matters.",
  "article248": "Grants residuary legislative powers to Parliament.",
  "article249": "Allows Parliament to legislate on State List matters in the national interest.",
  "article250": "Permits Parliament to legislate on State List matters during a national emergency.",
  "article251": "Addresses inconsistencies between Union and State laws under Articles 249 and 250.",
  "article252": "Allows Parliament to legislate for States by their consent.",
  "article253": "Empowers Parliament to legislate for implementing international agreements.",
  "article254": "Resolves inconsistencies between Union and State laws on Concurrent List matters.",
  "article255": "Treats recommendations and sanctions as procedural matters.",
  "article256": "Mandates States to comply with Union laws and directions.",
  "article257": "Provides for Union control over States in certain administrative matters.",
  "article258": "Allows the Union to confer powers or functions on States.",
  "article258A": "Permits States to entrust functions to the Union.",
  "article260": "Grants the Union jurisdiction over territories outside India.",
  "article261": "Ensures full faith and credit to public acts and judicial proceedings.",
  "article262": "Provides for adjudication of disputes over inter-State river waters.",
  "article263": "Establishes an Inter-State Council for coordination between States.",
  "article264": "Defines terms related to finance for Part XII.",
  "article265": "Prohibits taxes without legal authority.",
  "article266": "Establishes Consolidated Funds and public accounts for the Union and States.",
  "article267": "Provides for Contingency Funds for the Union and States.",
  "article268": "Details duties levied by the Union but collected by States.",
  "article269": "Lists taxes levied and collected by the Union but assigned to States.",
  "article269A": "Regulates levy and collection of GST in inter-State trade.",
  "article270": "Provides for distribution of taxes between the Union and States.",
  "article271": "Allows the Union to impose surcharges for its purposes.",
  "article273": "Provides grants in lieu of export duty on jute products.",
  "article274": "Requires Presidential recommendation for Bills affecting State taxation.",
  "article275": "Provides for grants from the Union to States.",
  "article276": "Allows States to levy taxes on professions, trades, and employments.",
  "article277": "Preserves certain State taxes existing before the Constitution.",
  "article279": "Provides for calculation of net proceeds of taxes.",
  "article279A": "Establishes a GST Council for tax-related coordination.",
  "article280": "Constitutes a Finance Commission to recommend financial distributions.",
  "article281": "Requires the President to lay Finance Commission recommendations before Parliament.",
  "article282": "Allows Union and States to make grants for public purposes.",
  "article283": "Regulates custody of Consolidated and Contingency Funds.",
  "article284": "Manages custody of suitors’ deposits and other moneys.",
  "article285": "Exempts Union property from State taxation.",
  "article286": "Imposes restrictions on taxation of goods in inter-State trade.",
  "article287": "Exempts electricity consumption by the Union from State taxes.",
  "article288": "Exempts State water or electricity projects from Union taxes.",
  "article289": "Exempts State property and income from Union taxation.",
  "article290": "Provides for adjustment of certain expenses between Union and States.",
  "article290A": "Mandates payments to certain Devaswom Funds.",
  "article292": "Regulates borrowing by the Government of India.",
  "article293": "Regulates borrowing by States.",
  "article294": "Details succession to property and rights between Union and States.",
  "article295": "Addresses succession to property and rights in other cases.",
  "article296": "Vests property accruing by escheat or lapse in the Union or States.",
  "article297": "Vests maritime resources in the Union.",
  "article298": "Grants Union and States power to carry on trade or business.",
  "article299": "Regulates contracts made by the Union and States.",
  "article300": "Regulates suits and legal proceedings involving the Union and States.",
  "article300A": "Prohibits deprivation of property except by authority of law.",
  "article301": "Ensures freedom of trade, commerce, and intercourse throughout India.",
  "article302": "Allows Parliament to impose restrictions on trade for public interest.",
  "article303": "Prohibits discriminatory restrictions on trade by Union or States.",
  "article304": "Allows States to impose reasonable restrictions on trade.",
  "article305": "Preserves existing laws and State monopolies from Part XIII restrictions.",
  "article307": "Allows Parliament to appoint an authority to regulate trade.",
  "article308": "Defines terms used in Part XIV regarding public services.",
  "article309": "Allows regulation of recruitment and service conditions for public services.",
  "article310": "Provides that public servants hold office at the pleasure of the President or Governor.",
  "article311": "Protects civil servants from arbitrary dismissal or reduction in rank.",
  "article312": "Empowers Parliament to create All-India Services.",
  "article312A": "Allows Parliament to vary service conditions of certain officers.",
  "article313": "Preserves existing service rules until new provisions are made.",
  "article315": "Establishes Public Service Commissions for the Union and States.",
  "article316": "Details appointment and term of Public Service Commission members.",
  "article317": "Provides for removal or suspension of Commission members.",
  "article318": "Allows regulations for Commission members’ conditions of service.",
  "article319": "Prohibits Commission members from holding certain offices after tenure.",
  "article320": "Outlines functions of Public Service Commissions.",
  "article321": "Allows extension of Commission functions by law.",
  "article322": "Provides for expenses of Public Service Commissions.",
  "article323": "Requires Commissions to submit annual reports.",
  "article323A": "Provides for establishment of administrative tribunals.",
  "article323B": "Allows tribunals for disputes in specified matters.",
  "article324": "Vests superintendence and control of elections in the Election Commission.",
  "article325": "Prohibits exclusion from electoral rolls on grounds of religion, race, caste, or sex.",
  "article326": "Provides for elections based on adult suffrage.",
  "article327": "Empowers Parliament to make laws for elections.",
  "article328": "Allows State Legislatures to make laws for State elections.",
  "article329": "Prohibits court interference in electoral matters.",
  "article330": "Provides for reservation of seats for Scheduled Castes and Tribes in Lok Sabha.",
  "article331": "Allows nomination of Anglo-Indians to the Lok Sabha.",
  "article332": "Provides for reservation of seats for Scheduled Castes and Tribes in State Assemblies.",
  "article333": "Allows nomination of Anglo-Indians to State Legislative Assemblies.",
  "article334": "Specifies the duration of reservations and Anglo-Indian nominations.",
  "article335": "Ensures claims of Scheduled Castes and Tribes in public services.",
  "article336": "Provides special provisions for Anglo-Indians in certain services.",
  "article337": "Provides educational grants for the Anglo-Indian community.",
  "article338": "Establishes a National Commission for Scheduled Castes.",
  "article338A": "Establishes a National Commission for Scheduled Tribes.",
  "article338B": "Establishes a National Commission for Backward Classes.",
  "article339": "Grants Union control over administration of Scheduled Areas and Tribes.",
  "article340": "Provides for a commission to investigate conditions of backward classes.",
  "article341": "Empowers the President to specify Scheduled Castes.",
  "article342": "Empowers the President to specify Scheduled Tribes.",
  "article342A": "Empowers the President to specify socially and educationally backward classes.",
  "article343": "Designates Hindi and English as official languages of the Union.",
  "article344": "Provides for a Commission to promote Hindi and review language use.",
  "article345": "Allows States to adopt official languages for their use.",
  "article346": "Specifies languages for communication between Union and States.",
  "article347": "Allows special provisions for languages spoken by sections of the population.",
  "article348": "Mandates English for Supreme Court, High Courts, and authoritative texts.",
  "article349": "Prescribes procedures for enacting laws on language use.",
  "article350": "Allows representations for grievance redressal in any language.",
  "article350A": "Mandates facilities for mother-tongue instruction at the primary stage.",
  "article350B": "Appoints a Special Officer for safeguarding linguistic minorities.",
  "article351": "Directs the Union to promote the development and spread of Hindi.",
  "article352": "Allows the President to proclaim a national emergency.",
  "article353": "Outlines the effects of a national emergency on Union and State powers.",
  "article354": "Modifies revenue distribution provisions during a national emergency.",
  "article355": "Imposes a duty on the Union to protect States from external aggression and internal disturbance.",
  "article356": "Allows President’s rule in a State upon failure of constitutional machinery.",
  "article357": "Grants legislative powers to the President during President’s rule.",
  "article358": "Suspends Article 19 rights during a national emergency.",
  "article359": "Allows suspension of other fundamental rights during an emergency.",
  "article360": "Provides for a financial emergency to address economic instability.",
  "article361": "Grants legal immunity to the President and Governors.",
  "article361A": "Protects publication of true reports of parliamentary proceedings.",
  "article361B": "Disqualifies certain officeholders from remunerative political posts.",
  "article363": "Prohibits court interference in disputes arising from certain treaties.",
  "article363A": "Abolishes recognition of princely rulers and privy purses.",
  "article364": "Provides special provisions for major ports and aerodromes.",
  "article365": "Addresses State failure to comply with Union directions.",
  "article366": "Defines key terms used throughout the Constitution.",
  "article367": "Provides rules for interpreting the Constitution.",
  "article368": "Outlines the procedure for amending the Constitution.",
  "article369": "Grants Parliament temporary powers over certain State List matters.",
  "article371": "Provides special provisions for Maharashtra and Gujarat.",
  "article371A": "Provides special provisions for Nagaland.",
  "article371B": "Provides special provisions for Assam.",
  "article371C": "Provides special provisions for Manipur.",
  "article371D": "Provides special provisions for Andhra Pradesh and Telangana.",
  "article371E": "Provides for establishment of a Central University in Andhra Pradesh.",
  "article371F": "Provides special provisions for Sikkim.",
  "article371G": "Provides special provisions for Mizoram.",
  "article371H": "Provides special provisions for Arunachal Pradesh.",
  "article371I": "Provides special provisions for Goa.",
  "article371J": "Provides special provisions for Karnataka.",
  "article372": "Allows continuance of pre-Constitution laws until altered.",
  "article372A": "Empowers the President to adapt existing laws.",
  "article373": "Allows Presidential orders for preventive detention.",
  "article374": "Provides for transition from Federal Court to Supreme Court.",
  "article375": "Ensures continuity of courts and authorities.",
  "article376": "Provides for continuation of High Court Judges.",
  "article377": "Provides for continuation of the Comptroller and Auditor-General.",
  "article378": "Provides for continuation of Public Service Commissions.",
  "article378A": "Specifies the duration of the Andhra Pradesh Legislative Assembly.",
  "article392": "Empowers the President to remove difficulties during transition.",
  "article393": "Designates the Constitution as the 'Constitution of India'.",
  "article394": "Specifies the commencement date of the Constitution as January 26, 1950.",
  "article394A": "Authorizes the Hindi translation as an authoritative text.",
  "article395": "Repeals the Indian Independence Act, 1947, and other laws.",
  "schedule1": "Lists the States and Union Territories of India.",
  "schedule2": "Specifies salaries and allowances for key officials like the President and Judges.",
  "schedule3": "Prescribes forms of oaths or affirmations for public officials.",
  "schedule4": "Details allocation of seats in the Council of States (Rajya Sabha).",
  "schedule5": "Provides for administration of Scheduled Areas and Scheduled Tribes.",
  "schedule6": "Details administration of tribal areas in Assam, Meghalaya, Tripura, and Mizoram.",
  "schedule7": "Distributes legislative powers through Union, State, and Concurrent Lists.",
  "schedule8": "Lists languages recognized by the Constitution.",
  "schedule9": "Lists laws protected from judicial review.",
  "schedule10": "Contains provisions to prevent defection by elected representatives.",
  "schedule11": "Lists powers and responsibilities assigned to Panchayats.",
  "schedule12": "Lists powers and responsibilities assigned to Municipalities.",
  "amendment1": "Added Articles 31A, 31B, and Ninth Schedule to protect land reforms.",
  "amendment7": "Reorganized States based on linguistic lines; repealed Part VII.",
  "amendment42": "Added Fundamental Duties (51A), Articles 323A, 323B; expanded Directive Principles.",
  "amendment44": "Added Article 300A; modified emergency provisions; restored judicial review.",
  "amendment69": "Added Articles 239AA, 239AB to provide special status for Delhi.",
  "amendment73": "Added Part IX and Eleventh Schedule to strengthen Panchayats.",
  "amendment74": "Added Part IX-A and Twelfth Schedule to strengthen Municipalities.",
  "amendment86": "Added Article 21A; amended Article 45 for compulsory education.",
  "amendment97": "Added Part IX-B to promote co-operative societies.",
  "amendment101": "Introduced Goods and Services Tax via Articles 269A, 279A.",
  "amendment102": "Added Articles 338B, 342A for Backward Classes Commission.",
};
